backend:
  name: git-gateway
  branch: main

media_folder: "assets/img"
public_folder: "/assets/img"

collections:
  - name: "productos"
    label: "Productos"
    folder: "productos"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Nombre", name: "titulo", widget: "string"}
      - {label: "Precio", name: "precio", widget: "number"}
      - {label: "Imagen", name: "imagen", widget: "image"}
      - {label: "Descripcion", name: "descripcion", widget: "markdown"}